In [ ]:
# Capstone Project - Employee_Project_Analysis
# Name: Akash Sonwalkar
# Description: This notebook contains solutions for all 10 tasks using pandas and numpy

In [ ]:
# Import required libraries
import numpy as np 
import pandas as pd

# TASK 1 :  Creating Dataframes from raw project data

In [ ]:
# Creating Project DataFrame
project = {
    'ID' : ['A001','A002','A003','A004','A005','A002','A005','A003','A001','A003','A001','A004','A004','A005'],
    'Project' : ['Project 1','Project 2','Project 3','Project 4','Project 5','Project 6','Project 7','Project 8','Project 9','Project 10','Project 11','Project 12','Project 13','Project 14'],
    'Cost' : [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],
    'Status' : ['Finished', 'Ongoing', 'Finished','Ongoing','Finished','Failed','Finished','Failed','Ongoing','Finished','Failed','Ongoing','Finished','Finished']
}
project_df = pd.DataFrame(project)

In [ ]:
project_df               # Displaying the DataFrame

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [ ]:
# Saving Project DataFrame in CSV file
project_df.to_csv('project.csv', index=False)

In [ ]:
# Creating Employee DataFrame
employee = {
    'ID' : ['A001','A002','A003','A004','A005'],
    'Name' : ['John Alter', 'Alice Luxumberg', 'Tom Sabestine', 'Nina Adgra', 'Amy Johny'],
    'Gender' : [ 'M','F','M','F','F'],
    'City' : ['Paris', 'London', 'Berlin', 'Newyork', 'Madrid'],
    'Age' : [ 25,27,29,31,30]
}
emp_df = pd.DataFrame(employee)

In [ ]:
emp_df                        # Displaying the DataFrame

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [ ]:
# Saving Employee DataFrame in CSV file
emp_df.to_csv('employee.csv', index = False)

In [ ]:
# Creating Seniority DataFrame
Seniority = {
    'ID' : ['A001','A002','A003','A004','A005'],
    'Designation Level' : [2,2,3,2,3]
}
slevel_df = pd.DataFrame(Seniority)

In [ ]:
print(slevel_df)                 # Displaying the DataFrame

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [ ]:
# Saving Seniority DataFrame in CSV file
slevel_df.to_csv('seniority_level.csv', index = False)

# TASK 2 : Fill missing values using running average

In [ ]:
# Load project data
df_proj = pd.read_csv('project.csv')

In [ ]:
df_proj                              # Displaying the DataFrame

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [ ]:
for i in range(len(df_proj)):                        # using for loop 
    if pd.isna(df_proj.loc[i, 'Cost']):              # applying if conditions to check null 
        
        prev_values = df_proj.iloc[:i]['Cost']       # all the values till null values
        
        avg = prev_values.mean()                # average values of number till null
        
        df_proj.loc[i, 'Cost'] = avg                # adding the calculated averge in place of null 
print(df_proj)                                       # printing the dataframe

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

  #  TASK 3 : Split Name Column and Remove Original Column

In [ ]:
# Load Employee data
df_emp = pd.read_csv('employee.csv')

In [ ]:
df_emp                                  # Displaying the DataFrame

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [ ]:
df_emp[['First Name','Last Name']] = df_emp['Name'].str.split(' ',expand = True)     # Splitting the 'Name' column into 'First Name' and 'Last Name'.

In [ ]:
df_emp[['First Name','Last Name']]

  First Name  Last Name
0       John      Alter
1      Alice  Luxumberg
2        Tom  Sabestine
3       Nina      Adgra
4        Amy      Johny

In [ ]:
df_emp.drop('Name' ,axis=1 , inplace = True)      # using drop function to remove the  original 'Name' column

In [ ]:
df_emp                            # Displaying the DataFrame

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

#  TASK 4 : Merging employee, project, and seniority datasets into a single dataframe

In [ ]:
# Load Seniority data
df_slevel = pd.read_csv('Seniority_level.csv')

In [ ]:
Final_df = pd.merge(df_proj,df_emp, on = 'ID')       # Merging  Project and Employee dataframes on 'ID'

In [ ]:
Final_df                                    # Displaying the merged dataframe

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny

In [ ]:
Final_df = pd.merge(Final_df,df_slevel, on = 'ID')         # Merging the result seniority dataframe on 'ID'

In [ ]:
Final_df                                    # Displaying the final merged dataframe

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3

# Task 5 : Create Bonus Column

In [ ]:
Final_df['Bonus'] = (Final_df['Status'] == 'Finished') * Final_df['Cost'] * 0.05  # Creating 'Bonus' column: 5% of Cost for 'Finished' projects, else 0

In [ ]:
Final_df                        # Displaying the DataFrame

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000.0

# Task 6 : Demote and Remove Employees

In [ ]:
Final_df.loc[Final_df['Status'] == 'Failed', 'Designation Level'] -= 1             # Decrease designation level by 1 for employees with 'Failed' status column

In [ ]:
Final_df = Final_df[Final_df['Designation Level'] <= 4]                        # Keep only rows where Designation Level is less than or equal to 4

In [ ]:
Final_df                                 # Displaying the DataFrame

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,1,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,2,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,1,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000.0

# Task 7 : Add Mr & Mrs to First Name and Drop Gender Column

In [ ]:
# Adding 'Mr' for males and 'Mrs' for females in the First Name column
Final_df.loc[Final_df['Gender'] == 'M', 'First Name'] = 'Mr' + ' ' + Final_df['First Name']
Final_df.loc[Final_df['Gender'] == 'F', 'First Name'] = 'Mrs' + ' ' + Final_df['First Name']

In [ ]:
Final_df                                 # Displaying the DataFrame

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,Mr John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Mrs Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Mr Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Mrs Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Mrs Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Mrs Alice,Luxumberg,1,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Mrs Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Mr Tom,Sabestine,2,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,Mr John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Mr Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,Mr John,Alter,1,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Mrs Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Mrs Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Mrs Amy,Johny,3,10000.0

In [ ]:
Final_df.drop('Gender', axis = 1 , inplace = True)                       # using drop function to drop 'Gender' column from the dataframe

In [ ]:
Final_df                  # Displaying the final dataframe

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs Alice,Luxumberg,1,0.0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr Tom,Sabestine,2,0.0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr John,Alter,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs Amy,Johny,3,10000.0

# Task 8 : Promotion using IF Condition

In [ ]:
for i in range(len(Final_df)) :                         # Using a for loop to iterate through the DataFrame
    if Final_df.loc[i,'Age'] > 29 :                    # Applying IF condition to check Age > 29                    
        Final_df.loc[i,'Designation Level'] += 1       # Increasing Designation Level by 1 if condition is satisfied

In [ ]:
Final_df                          # Displaying the DataFrame

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs Nina,Adgra,3,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs Amy,Johny,4,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs Alice,Luxumberg,1,0.0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs Amy,Johny,4,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr Tom,Sabestine,2,0.0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr John,Alter,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs Nina,Adgra,3,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs Nina,Adgra,3,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs Amy,Johny,4,10000.0

# Task 9 : Calculate Total Project Cost per Employee

In [ ]:
TotalProjCost = Final_df.groupby(['ID','First Name'])['Cost'].sum().reset_index()   # Creating new DataFrame using groupby and sum aggregation

In [ ]:
TotalProjCost                         # Displaying the aggregated DataFrame

     ID First Name       Cost
0  A001    Mr John  5212312.5
1  A002  Mrs Alice  2680000.0
2  A003     Mr Tom  5150000.0
3  A004   Mrs Nina  9500000.0
4  A005    Mrs Amy  3850500.0

In [ ]:
TotalProjCost.rename(columns = {'Cost' : 'Total Cost'}, inplace = True)            # Renaming 'Cost' column to 'Total Cost'

In [ ]:
TotalProjCost                              # Displaying the DataFrame

     ID First Name  Total Cost
0  A001    Mr John   5212312.5
1  A002  Mrs Alice   2680000.0
2  A003     Mr Tom   5150000.0
3  A004   Mrs Nina   9500000.0
4  A005    Mrs Amy   3850500.0

# Task 10 : Print all the Employee Details

In [ ]:
Final_df                        # Displaying the DataFrame

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs Nina,Adgra,3,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs Amy,Johny,4,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs Alice,Luxumberg,1,0.0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs Amy,Johny,4,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr Tom,Sabestine,2,0.0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr John,Alter,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs Nina,Adgra,3,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs Nina,Adgra,3,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs Amy,Johny,4,10000.0

In [ ]:
Result = Final_df[Final_df['City'].str.contains('o', case=False)]         # Filtering rows where City contains letter 'o'

In [ ]:
Result                              # Displaying the DataFrame

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs Alice,Luxumberg,2,0.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs Nina,Adgra,3,0.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs Alice,Luxumberg,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs Nina,Adgra,3,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs Nina,Adgra,3,150000.0

In [ ]:
# Final Insights

# Employees with completed projects received performance bonuses.
# Failed projects affected designation levels.
# Project costs were aggregated to evaluate employee contributions.
# Data cleaning and transformation improved dataset usability.